-- Project Midnight default database setup
CREATE USER IF NOT EXISTS "user"@localhost IDENTIFIED BY "";
CREATE SCHEMA MIDNIGHT;
GRANT ALL PRIVELEGES ON MIDNIGHT.* TO "user"@localhost IDENTIFIED BY "";
USE MIDNIGHT;
CREATE TABLE `user` (
	`ID` INT(3) NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(20) NOT NULL,
	`WORD` VARCHAR(20) NOT NULL DEFAULT '00000000',
	`ASTAT` BIT(1) NULL DEFAULT b'0',
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `cipher` (
	`ID` INT(6) NOT NULL,
	`NAME` VARCHAR(20) NOT NULL,
	`UID` INT(3) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	INDEX `UID` (`UID`),
	CONSTRAINT `cipher_ibfk_1` FOREIGN KEY (`UID`) REFERENCES `user` (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `symbol` (
	`ID` INT(13) NOT NULL,
	`SYM` VARCHAR(1) NOT NULL,
	`CID` INT(6) NULL DEFAULT NULL,
	`UID` INT(3) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	INDEX `CID` (`CID`),
	INDEX `UID` (`UID`),
	CONSTRAINT `symbol_ibfk_1` FOREIGN KEY (`CID`) REFERENCES `cipher` (`ID`),
	CONSTRAINT `symbol_ibfk_2` FOREIGN KEY (`UID`) REFERENCES `user` (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `security` (
	`ID` INT(15) NOT NULL AUTO_INCREMENT,
	`QUE` VARCHAR(50) NOT NULL,
	`ANS` VARCHAR(50) NOT NULL,
	`UID` INT(3) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	INDEX `UID` (`UID`),
	CONSTRAINT `security_ibfk_1` FOREIGN KEY (`UID`) REFERENCES `user` (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `logs` (
	`ID` INT(15) NOT NULL AUTO_INCREMENT,
	`REC` DATETIME NOT NULL DEFAULT current_timestamp(),
	`CID` INT(6) NULL DEFAULT NULL,
	`UID` INT(3) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	INDEX `CID` (`CID`),
	INDEX `UID` (`UID`),
	CONSTRAINT `logs_ibfk_1` FOREIGN KEY (`CID`) REFERENCES `cipher` (`ID`),
	CONSTRAINT `logs_ibfk_2` FOREIGN KEY (`UID`) REFERENCES `user` (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
INSERT INTO USER(NAME, WORD, ASTAT) VALUES ("admin", "projectmidnightadmin", 1);
INSERT INTO SECURITY(QUE, ANS, UID) VALUES ("What is the crystal latice of Enthereon?", "Midnight Sky", 1);
